// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateAppAPI.Model;

namespace RealEstateAppAPI.Migrations
{
    [DbContext(typeof(RealEstateDBContext))]
    partial class RealEstateDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("RealEstateAppAPI.Model.Houses", b =>
                {
                    b.Property<int>("HouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("City")
                        .HasColumnType("nvarcar(100)");

                    b.Property<int>("NumBaths")
                        .HasColumnType("int");

                    b.Property<int>("NumBedrooms")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarcar(100)");

                    b.Property<int>("SquareFeet")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarcar(14)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarcar(100)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarcar(100)");

                    b.HasKey("HouseID");

                    b.ToTable("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
